version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "vebinar_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "8001:8001"
    links:
      - db
    depends_on:
      - db


  ui:
    build: ./web_ui
    ports:
      - "8000:8000"
    links:
      - api
      - db
    depends_on:
      - api


