FROM tiangolo/uvicorn-gunicorn:python3.11

COPY ./api /app

EXPOSE 8001
EXPOSE 5432

RUN --mount=type=cache,target=/root/.cache \
    pip install -r /app/requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]